spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskapp
    username: taskapp
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoint.health.probes.enabled: true
  endpoints.web.exposure:
    include: health, beans
